actors:
  Tachu:
    image_url: /images/actors/alice.png
    name: タチュ
    url: https://twitter.com/Imokenpiman
  bob:
    image_url: /images/actors/bob.png
    name: bob
    url: http://sns.example.com/bob
author: Tachu
description: 説明文
description_long: 長い説明文
email: testcopyrights+beat333
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: beat333
itunes_podcast_url:
keywords: 雑談,フリートーク
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: 三三三拍子
url: https://twitter.com/Imokenpiman
